### ISSUE TITLE
Dealing with padded encodings

### ISSUE THREAD

**Issue by whyrusleeping** [multiformats/multibase#9] opened 2016-08-22 19:18 UTC
Should we discriminate between padded and unpadded versions of encodings? For example, base32 and base64 can be used with or without padding, but most parsers will fail to parse one if it has padding when its not expected, and visa versa

**Comment by lgierth** [comment] 2016-08-23 00:18
accept padded but emit non-padded?

**Comment by kevina** [comment] 2016-08-23 03:37
I think we may have to as annoying as it is.  base64url should leave them off my default, base64 should have them, I suppose base32 should have then but we should provide another encoded that doesn't and matches what we use in the datastore.

**Comment by kevina** [comment] 2016-08-23 05:47
Now that I thought about it some more I propose the default encoding leave the pad off (but possible accept them when decoding) and provide an encoding with padding by appending '=' (the padding character for base32 and base64 encoding) after the identifier.  For example:
```
u  base 32 no padding
u= base 32 with padding
y  base 64 no padding
y= base 64 with padding
```
The rfc4685 section 3.2 says
```
 Implementations MUST include appropriate pad characters at the end of
 encoded data unless the specification referring to this document
 explicitly states otherwise.
```
I consider our specification that padding is not used to qualify as "explicitly states otherwise".

**Comment by jbenet** [comment] 2016-08-23 06:13
I like the idea of adding "options" through another char in the identifier. This would make the multibase prefix variable though, without clear rule when the identifier is there and when it's not. which isn't ideal. but i see the appeal. "may be followd by =" is not great. I would almost prefer to always have another char. not sure if this is the right solution though-- if the number of "padding bases" is small, we could use another char in the alphabet.

**Comment by kevina** [comment] 2016-08-23 06:23
My thought on using '=' is that the only other place '=' can be used in base32 and base64 is at the end, so there is no confusion.

**Comment by jbenet** [comment] 2016-08-23 22:34
Hm, i think there's likely things out there that just strip out `=`s. this kind of thing may have adverse consequences. though i guess it would "work as intended" in this case.

@kevina it would be valuable to figure out how many other encodings there are per base, and see if it warrants spending another char on the wire or on the table for those?

**Comment by kevina** [comment] 2016-08-23 23:55
@jbenet according to Wikipedia (https://en.wikipedia.org/wiki/Base32#Alternative_versions) there are at least 3 more versions of base-32 in use, I am not sure how common they are: z-base-32, Crockford's Base32, Electrologica.  For base-64 there is a huge list of variant encoding for base-64 (https://en.wikipedia.org/wiki/Base64#Variants_summary_table).  For now I think it would be a good idea to stick with the standard encoding unless we determine the other encoding will be useful.

It is important to note that a lot use for base-64 (and possible base-32 and base-85) is for encoding content is a transmission safe manor, not for encoding short hash strings.

As far as with or without padding, I am not sure.  A lot of why padding is used is because standard encoders sometimes require it.  The use of padding likely stems from the original base64 used in MIME encoding and isn't really useful for hash encoding.

Due to the encoder situation, I think both base32 and base64url is used with and without padding in the wild, but I am no expert.  It is worth nothing that we (me, @whyrusleeping and @Kubuxu) made it a point to exclude the padding from base32 when we chose it for the datastore .  I don't think base64 us used much for hash encoding.

That being said, if you want to assign new letters for with and without padding this is what I would propose (from #10):
```
base32        H, h    rfc4648 - no padding
base32        I, i    rfc4648 - with padding
base64        m       rfc4648 no padding -- I don't see a use for this combination, but included for completness
base64        M       rfc4648 with padding -- used primary for MIME, unlikely to be used for hash encoding
base64url     u       rfc4648 no padding
base64url     U       rfc4648 with padding
```
Just a suggestion, I don't want to bike shed on this If you don't like my assignments I will go with whatever you think is best.

**Comment by jbenet** [comment] 2016-08-24 00:53
This looks pretty good. Let's do this:
- If we go with a second char, we will revisit this to use it to handle padding.
- For now go with this line of thinking.
- I would prefer to keep base64 close to base64url, but i guess it's not necessary and the MIME connection will make someone smile in the future.
- one problem: your assignments reassign capitals-- ie. in base64 case they denote padding, in the base32 case they dont. maybe `H,h` for padding,no padding of one version, and `I, i` for padding, no padding of the other version? (ie make the cap be padding, or vice versa, if you want to see caps more often)

on base32s
- `base32` keep
- `base32hex` keep
- `base32z` i think we should have z-base-32. making multibase usable for Tahoe-LAFS would be nice plus. (i call it `base32z` here to fit our notation. we can just keep a reference here and in mention it in the table that it is known as `z-base-32` more widely.
- i dont think we need Crockfords (which involves checksums, not just an encoding) or Electrologica just yet.

**Comment by jbenet** [comment] 2016-08-24 00:53
otherwise your suggestions LGTM

**Comment by kevina** [comment] 2016-08-24 01:04
> one problem: your assignments reassign capitals-- ie. in base64 case they denote padding, in the base32 case they dont. maybe H,h for padding,no padding of one version, and I, i for padding, no padding of the other version? (ie make the cap be padding, or vice versa, if you want to see caps more often)

I did this because base32 can can be case insensitive so it will be problematic to distinguish on case, also technically lowercase 'h' is not in the encoding which is uppercase.

**Comment by jbenet** [comment] 2016-08-24 01:05
> case insensitive

Ah, that's right! nevermind.

**Comment by jbenet** [comment] 2016-08-24 01:06
want to show the full diff to the table in a PR? (can you add `base32z` ?)

**Comment by kevina** [comment] 2016-08-24 01:12
> want to show the full diff to the table in a PR 

Sure

>(can you add base32z ?)

Yes

**Comment by kevina** [comment] 2016-08-24 01:47
@jbenet see #11

**Comment by vmx** [comment] 2020-06-09 10:41
That long ago to merged.

**Closed by vmx** 2020-06-09 10:41 UTC
